### ISSUE TITLE
Payment Gateway Giving Error Checksum Mismatch

### ISSUE THREAD

**Issue by anuragco** [anuragco/Netflix-Clone#1]
**I have used an Upi Gateway and with the help of docs I have successfully passed all the parameters and those parameters get accepted by the gateway But I got an issue in generating checksum. I tried many things but all failed, I have integrated the payment into this page "/home-page/forgetpasswordhelper/conformpayment.html", and I also have server-side checksum code in PHP, please review my repo where I am missing.**

**I got an Integration kit from The UPIFAST that is server-side code : https://github.com/officialmastcoder/Upifast_lib**

**Comment by iamirulhkhan** [comment]
Now I have Added it properly check it out

**Comment by anuragco** [comment]
It's Working Thank You So Much
